spring:
  application:
    name: eureka-server

server:
  port: 8002

eureka:
  instance:
    hostname: localhost2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost1:8001/eureka/,http://localhost3:8003/eureka/