spring:
  application:
    name: eureka-server

server:
  port: 8003

eureka:
  instance:
    hostname: localhost3
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost1:8001/eureka/,http://localhost2:8002/eureka/