spring:
  application:
    name: dateTime-service
  cloud:
    config:
      server:
        health:
          repositories:

server:
  port: 18002

eureka:
  instance:
    hostname: localhost2
  client:
    serviceUrl:
      defaultZone: http://localhost1:8001/eureka/,http://localhost2:8002/eureka/,http://localhost3:8003/eureka/

management:
  security:
    enabled: false
